### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by koeppel** [krlittle/SpringAndBlizzard#1]
Hello,

I have copied your project and tried it out myself. I was using ngrok.io to test the api call to Balltle.net.

The spring application crashes after trying to OAuth with following Output:
"Could not fetch user details: class org.springframework.web.client.HttpClientErrorException, 401 Unauthorized"

Are you still working on this?

**Comment by krlittle** [comment]
Hi, thanks for checking out my project!

Would you mind pointing me to your code?
Could you also provide a stack trace?

Thanks! :)

**Comment by koeppel** [comment]
Hi,

sorry, I didn't notice that you replied. I actually managed to fix the problem by myself. I'm actually not sure how because it's 3 months ago.. 

Thanks anyway!
